export const PlotVotingABI = [
  // Events
  {
    type: 'event',
    name: 'ProposalSubmitted',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'author', type: 'address', indexed: true },
      { name: 'storyId', type: 'uint256', indexed: true },
      { name: 'contentHash', type: 'string', indexed: false },
      { name: 'stakeAmount', type: 'uint256', indexed: false },
      { name: 'deadline', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VoteCommitted',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'voter', type: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VoteRevealed',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'voter', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'totalVotes', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'commitVote',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'commitment', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revealVote',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'voteAmount', type: 'uint256' },
      { name: 'salt', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'enableConfidentialVoting',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'commitDuration', type: 'uint256' },
      { name: 'revealDuration', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getProposalPrivacy',
    stateMutability: 'view',
    inputs: [ { name: 'proposalId', type: 'uint256' } ],
    outputs: [
      { name: 'confidential', type: 'bool' },
      { name: 'commitDeadline', type: 'uint256' },
      { name: 'revealDeadline', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'hasCommitted',
    stateMutability: 'view',
    inputs: [ { name: 'proposalId', type: 'uint256' }, { name: 'voter', type: 'address' } ],
    outputs: [ { name: '', type: 'bool' } ],
  },
  {
    type: 'function',
    name: 'hasRevealed',
    stateMutability: 'view',
    inputs: [ { name: 'proposalId', type: 'uint256' }, { name: 'voter', type: 'address' } ],
    outputs: [ { name: '', type: 'bool' } ],
  },
  {
    type: 'event',
    name: 'VoteCast',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'voter', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'totalVotes', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalExecuted',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'storyId', type: 'uint256', indexed: true },
      { name: 'author', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalRejected',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'storyId', type: 'uint256', indexed: true },
      { name: 'author', type: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'vote',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'voteAmount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'stakeForProposal',
    stateMutability: 'payable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'executeProposal',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'rejectProposal',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getProposal',
    stateMutability: 'view',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [
      { name: 'storyId', type: 'uint256' },
      { name: 'author', type: 'address' },
      { name: 'contentHash', type: 'string' },
      { name: 'chapterNumber', type: 'uint256' },
      { name: 'voteCount', type: 'uint256' },
      { name: 'stakeAmount', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
      { name: 'executed', type: 'bool' },
      { name: 'rejected', type: 'bool' },
      { name: 'totalVoters', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getTotalProposals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getStoryProposals',
    stateMutability: 'view',
    inputs: [{ name: 'storyId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'hasVoted',
    stateMutability: 'view',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'voter', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getVoteAmount',
    stateMutability: 'view',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'voter', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getUserSubmissions',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
] as const;
